started new interpolation (CubicSplines) which is a combination of linear + polynomial interpolation -> I only need the apache math commons library for this, but unfortunately I constantly receive "NoClassDefFoundError" although it is included -> ask prof next week?